version: '3.9'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    #    hostname: '192.168.2.220'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://ip'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['gitlab_shell_ssh_port'] = 9022
    ports:
      - '9080:80'
      - '9443:443'
      - '9022:22'
    volumes:
      - '/root/docker/gitlab/config:/etc/gitlab'
      - '/root/docker/gitlab/logs:/var/log/gitlab'
      - '/root/docker/gitlab/data:/var/opt/gitlab'

